// This file was autogenerated by calcdeps.py
goog.addDependency("../../../src/main/javascript/org/bigdesk/store/Manager.js", ['org.bigdesk.store.Manager'], ['org.bigdesk.net.XhrService', 'goog.async.Delay', 'goog.object', 'goog.Uri', 'goog.Disposable']);
goog.addDependency("../../../src/main/javascript/org/bigdesk/store/Store.js", ['org.bigdesk.store.Store'], ['goog.array', 'goog.Disposable']);
