// This file was autogenerated by calcdeps.py
goog.addDependency("../../../src/main/javascript/org/bigdesk/store/Manager.js", ['org.bigdesk.store.Manager', 'org.bigdesk.store.Manager.EventType'], ['org.bigdesk.store.event.NodesStatsAdd', 'org.bigdesk.store.event.NodesInfoAdd', 'org.bigdesk.store.Store', 'org.bigdesk.net.DefaultServiceProvider', 'goog.async.Delay', 'goog.object', 'goog.Uri', 'goog.events.EventTarget', 'goog.events', 'goog.debug.Logger']);
goog.addDependency("../../../src/main/javascript/org/bigdesk/store/Store.js", ['org.bigdesk.store.Store'], ['goog.array', 'goog.Disposable']);
goog.addDependency("../../../src/main/javascript/org/bigdesk/store/event/NodesInfoAdd.js", ['org.bigdesk.store.event.NodesInfoAdd'], ['org.bigdesk.store.Manager.EventType', 'goog.events.Event']);
goog.addDependency("../../../src/main/javascript/org/bigdesk/store/event/NodesInfoRemove.js", ['org.bigdesk.store.event.NodesInfoRemove'], ['org.bigdesk.store.Manager.EventType', 'goog.events.Event']);
goog.addDependency("../../../src/main/javascript/org/bigdesk/store/event/NodesStatsAdd.js", ['org.bigdesk.store.event.NodesStatsAdd'], ['org.bigdesk.store.Manager.EventType', 'goog.events.Event']);
goog.addDependency("../../../src/main/javascript/org/bigdesk/store/event/NodesStatsRemove.js", ['org.bigdesk.store.event.NodesStatsRemove'], ['org.bigdesk.store.Manager.EventType', 'goog.events.Event']);
goog.addDependency("../../../src/main/javascript/org/bigdesk/net/DefaultServiceProvider.js", ['org.bigdesk.net.DefaultServiceProvider'], ['org.bigdesk.net.Service', 'org.bigdesk.net.ServiceProvider', 'org.bigdesk.net.XhrService', 'org.bigdesk.net.JsonpService', 'goog.Uri']);
goog.addDependency("../../../src/main/javascript/org/bigdesk/net/JsonpService.js", ['org.bigdesk.net.JsonpService'], ['org.bigdesk.net.Service']);
goog.addDependency("../../../src/main/javascript/org/bigdesk/net/Service.js", ['org.bigdesk.net.Service'], []);
goog.addDependency("../../../src/main/javascript/org/bigdesk/net/ServiceProvider.js", ['org.bigdesk.net.ServiceProvider'], ['org.bigdesk.net.Service', 'goog.Uri']);
goog.addDependency("../../../src/main/javascript/org/bigdesk/net/XhrService.js", ['org.bigdesk.net.XhrService'], ['org.bigdesk.net.Service', 'goog.string', 'goog.net.XhrManager', 'goog.net.XhrManager.Event', 'goog.net.XhrManager.Request', 'goog.Uri', 'goog.Disposable']);
goog.addDependency("../../../src/test/javascript/org/bigdesk/net/TestService.js", ['org.bigdesk.net.TestService'], ['org.bigdesk.net.Service', 'goog.debug.Logger']);
goog.addDependency("../../../src/test/javascript/org/bigdesk/net/TestServiceProvider.js", ['org.bigdesk.net.TestServiceProvider'], ['org.bigdesk.net.Service', 'org.bigdesk.net.ServiceProvider', 'org.bigdesk.net.TestService', 'goog.Uri']);
