// This file was autogenerated by calcdeps.py
goog.addDependency("../../../src/main/javascript/org/bigdesk/store/Manager.js", ['org.bigdesk.store.Manager', 'org.bigdesk.store.Manager.EventType'], ['org.bigdesk.net.Service', 'org.bigdesk.net.ServiceProvider', 'org.bigdesk.net.DefaultServiceProvider', 'goog.async.Delay', 'goog.object', 'goog.Uri', 'goog.events', 'goog.events.EventTarget']);
goog.addDependency("../../../src/main/javascript/org/bigdesk/store/Store.js", ['org.bigdesk.store.Store'], ['goog.array', 'goog.Disposable']);
goog.addDependency("../../../src/main/javascript/org/bigdesk/store/event/NodesInfoAdd.js", ['org.bigdesk.store.event.NodesInfoAdd'], ['org.bigdesk.store.Manager.EventType', 'goog.events.Event']);
goog.addDependency("../../../src/main/javascript/org/bigdesk/store/event/NodesInfoRemove.js", ['org.bigdesk.store.event.NodesInfoRemove'], ['org.bigdesk.store.Manager.EventType', 'goog.events.Event']);
goog.addDependency("../../../src/main/javascript/org/bigdesk/store/event/NodesStatsAdd.js", ['org.bigdesk.store.event.NodesStatsAdd'], ['org.bigdesk.store.Manager.EventType', 'goog.events.Event']);
goog.addDependency("../../../src/main/javascript/org/bigdesk/store/event/NodesStatsRemove.js", ['org.bigdesk.store.event.NodesStatsRemove'], ['org.bigdesk.store.Manager.EventType', 'goog.events.Event']);
